global:
  scrape_interval: 3s #интервал сборки метрик( каждые 3 секунды)

scrape_configs:
  - job_name: "litestar" # название задачи сбора метрик
    metrics_path: /metrics # путь к endpoint, откуда брать метрики
    static_configs:
      - targets: ["backend:7070"] #адрес и порт целевого сервиса, с которых собирать данные(backend - имя docker-контейнера)